### ISSUE TITLE
nix package build issue

### ISSUE THREAD

**Issue by xaizek** [RSKYS/SBo-git#157]
For a long while I thought that the package is completely broken because I couldn't build it, so I installed newer `nix` via `nix` itself as a workaround after it stopped installing packages.  There were no `nix` package updates for some time, so I thought that's expected, but not being able to build even recent releases gave me an idea of removing `nix` before building a new version and that worked well.  From what I can tell `nix`'s build system picks up installed libraries while building tests instead of using yet-to-be-installed ones.  This was true even today for 2.17.2 on Slackware-current despite me originally having trouble with this on Slackware 15.0 probably couple years ago.  Am I the only one experiencing this?

This brings me to a question about tests, which are built, but not run.  I think they should either be built and executed or not build at all (there might be some value for just building tests for libraries, but I'd still run them).  In this case at least 2 dependencies are for only tests and seems like they could be eliminated and build time reduced by adding `--disable-tests`.

By the way, thanks for maintaining it.

**Comment by RSKYS** [comment]
Hello @xaizek! Welcome to SBo-git.
Yeah, I've been away from this package for quiet while but I started using Slackware again and nix; this time I'm not going anywhere ;)
Patching it has been quiet headache though but I managed to do it this far on 15.

>  In this case at least 2 dependencies are for only tests and seems like they could be eliminated and build time reduced by adding `--disable-tests`.

This is very good idea actually, on second thought, they're kinda unnecessary..
Thanks! I keep you posted with possible changes.

> By the way, thanks for maintaining it.

Your welcome! glad you're enjoying it.

**Comment by RSKYS** [comment]
Oh I didn't intend to make so many comments, didn't see these coming xD 
Anyway it seems something is really wrong with Slackware 15. I can't upgrade nix any further; just like I mentioned in LQ. 

Certain components are deprecated from this version onward.

**Comment by RSKYS** [comment]
> Certain components are deprecated from this version onward.

You could still use nix on "current" branch of this repo; I'm gonna revoke tests on that too + a little bit bump, later.
Okay @xaizek, I'm gonna submit this on slackbuilds and by the time it's merged to official's master, I'm gonna mark this issue as resolved.

**Comment by xaizek** [comment]
> Oh I didn't intend to make so many comments, didn't see these coming xD

References don't generate any notifications.

I just tried building `nix` from https://github.com/RSKYS/slackbuildsorg/commit/cc80009241d36e02e05a3059afc8c7ad6da8a63d after uninstalling `gtest` and `librapidcheck` (but not touching already installed `nix`) and it worked without any trouble.  Thanks!

**Comment by RSKYS** [comment]
Okay, the very last commit referenced here meant for Slackware Current and will not work on 15.

**Comment by RSKYS** [comment]
LGTM
